spring.application.name=StudentManagementSystemBYSwapDev
spring.datasource.url=jdbc:postgresql://localhost:5432/Student_db
spring.datasource.username=postgres
spring.datasource.password=swapdev11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081